version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: ./docker/php/Dockerfile
    container_name: sayway_api
    restart: always
    volumes:
      - sayway_sources:/var/www
      - ./api/.env:/var/www/.env
    depends_on:
      - db
    networks:
      - sayway_backend
      - sayway_services

  web:
    image: nginx:alpine
    container_name: sayway_web
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./api/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - sayway_sources:/var/www
    depends_on:
      - api
    networks:
      - sayway_backend
      - sayway_services

  db:
    image: postgres:16
    container_name: sayway_db
    restart: always
    environment:
      POSTGRES_DB: sayway
      POSTGRES_USER: sayway
      POSTGRES_PASSWORD: sayway
    ports:
      - "5432:5432"
    networks:
      - sayway_backend
    volumes:
      - sayway_data:/var/lib/postgresql/data

  nlp_service:
    build:
      context: ./services/nlp-service-camembert
      dockerfile: Dockerfile
    env_file:
      - ./services/nlp-service-camembert/.env
    container_name: sayway_nlp
    restart: always
    ports:
      - "5000:8000"
    volumes:
      - ./services/nlp-service-camembert:/app
    networks:
      - sayway_backend
      - sayway_services

  pathfinder_service:
    build:
      context: ./services/pathfinder-service
      dockerfile: Dockerfile
    env_file:
      - ./services/pathfinder-service/.env
    container_name: sayway_pathfinder
    restart: always
    ports:
      - "5050:8000"
    volumes:
      - ./services/pathfinder-service:/app
    networks:
      - sayway_backend
      - sayway_services

  queue:
    build:
      context: ./api
      dockerfile: ./docker/php/Dockerfile
    container_name: sayway_queue
    restart: always
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90 --queue=nlp_service,pathfinder_service
    volumes:
      - sayway_sources:/var/www
      - ./api/.env:/var/www/.env
    depends_on:
      - db
      - api
    networks:
      - sayway_backend
      - sayway_services

networks:
  sayway_backend:
  sayway_services:

volumes:
  sayway_data:
  sayway_sources: